# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7b811942cf9a6e2f325bb0b1c52e62ed07da6f3b54b1ad6b5165648fd1fc28e6c2230e5cc9d8da7b3764c64706e045d8d35c917623be5251adac2ed03657faf

test:
  secret_key_base: a99fb9bdf9dcec44a5dbfda147f35b492b3ebce6730573fd0623512e8864b9e65cc427e43133ee2da521dae905939f4fb02f164800b0cfdff48fb61af3ceadbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
